// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Configure a seed command so `pnpm prisma db seed` runs our seed script.
    // Use `tsx` to run the TypeScript seed directly (tsx is installed as a dev dependency).
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Use a direct Postgres connection for Prisma schema operations.
    // Pooler URLs can hang/fail for db push/migrate in Supabase setups.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
